# Generated by Django 2.2.5 on 2020-06-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='inventory_name',
            new_name='inventory_file',
        ),
    ]
